### ISSUE TITLE
Wrong winning cards

### ISSUE THREAD

**Issue by rchintan7** [WohligTechnology/teenpatti-solver#1]
Hello dear,

I have one issue facing in this library. Please help me out. 
Here is the issue with player.
A Player: JD, JC, AC
B Player: 8D, JH, JS
Result : winning player are B. But actual wining player are A

Thanks & Regards
C

**Comment by lcrocker** [comment]
I confirm:

> tps.scoreHandsNormal(['Jd', 'Jc', 'Ac'])
{ name: 'Pair', desc: 'Pair of J', score: 1110100 }
> tps.scoreHandsNormal(['8d', 'Jh', 'Js'])
{ name: 'Pair', desc: 'Pair of J', score: 1110800 }

It appears to be scoring the Ace as low here, adding only 100 for it, rather than high.

**Comment by wohlig** [comment]
We will resolve the issue.

**Comment by wohlig** [comment]
Thanks for pointing that out. We will surely resolve the issue. Thank you.

**Comment by rchintan7** [comment]
Can you please tell me when it's resolve this issue.

**Comment by wohlig** [comment]
Hi, the issue is resolved. Please download the new version of NPM teenpattisolver@1.1.5
https://www.npmjs.com/package/teenpattisolver.  Thank you for pointing this issue. And let us know if there any more such issues.
